name: Lint and Format Code

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["*"]

jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Install goimports
        run: make install-tools-goimports
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
